services:
  firebase_emulators:
    image: fixl/firebase-emulator-suite
    networks:
      - tempsy_net
    ports:
      - 4000:4000
      - 9199:9199
    restart: on-failure
    environment:
      - STORAGE=true
      - FIREBASE_PROJECT_ID=$COMPOSE_PROJECT_NAME
    volumes:
      - ../configs/tempsy/storage.rules:/storage.rules
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M

networks:
  tempsy_net:
    name: tempsy_net