services:
  firebase_emulators:
    container_name: firebase_emulators
    image: afifurrohman/tiny-firebase
    networks:
      - tempsy_net
    ports:
      - 4000:4000
      - 9999:9999
    restart: on-failure
    command: firebase emulators:start -P $COMPOSE_PROJECT_NAME
    volumes:
      - tempsy_data:/root/.cache/firebase
      - ../configs/firebase.json:/firebase/firebase.json
      - ../configs/storage.rules:/firebase/storage.rules

volumes:
  tempsy_data:

networks:
  tempsy_net:
    name: tempsy_net