on: 
    workflow_call:
      inputs:
        foo: 
          required: true
          type: string
      outputs:
        key:
            value: ${{jobs.test.outputs.key}}

jobs:
    test:
        strategy:
          matrix:
            foo:
              - bar: 1
                id: 1
                a: 1
                b: 1
              - ok: 2
                id: 2
                a: 2
                b: 2

        environment: staging
        runs-on: ubuntu-latest
        outputs:
          key: ${{steps.ok.outputs.key}}
        steps:
            - id: ok
              run: | 
                echo Foo: ${{inputs.foo}}
                echo Run on: ${{secrets.OK}}
                echo key=oooooooooooooooo >> $GITHUB_OUTPUT 
                echo ${{matrix.foo.a}}
                echo ${{matrix.foo.ok}}

