name: Ci Cd Staging Environment

on:
  pull_request:
    branches: main

jobs:
  try:
    strategy:
      matrix:
        foo:
          - bar: 1
            id: 1
            a: 1
            b: 1
          - ok: 2
            id: 2
            a: 2
            b: 2
    uses: ./.github/workflows/deploy.yaml
    with:
      foo: ${{matrix.foo.id}}-${{matrix.foo.a}}
    secrets: inherit
  out:
    runs-on: ubuntu-latest
    needs: try
    steps:
        - run: echo ${{needs.try.outputs.key}}          