name: Ci Cd Staging Environment

on:
  pull_request:
    branches: main

jobs:
  try:
    runs-on: ubuntu-latest
      
    steps:
      - uses: ./.github/workflows/deploy.yaml
        with:
          foo: bar

          