name: Ci Cd Staging Environment

on:
  pull_request:
    branches: main

jobs:
  try:
    uses: ./.github/workflows/deploy.yaml
    with:
      foo: bar
    secrets: inherit
  out:
    runs-on: ubuntu-latest
    needs: try
    steps:
        - run: echo ${{needs.try.outputs.key}}          