name: Ci Cd Staging Environment

on:
  pull_request:
    branches: main

jobs:
  try:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - id: run
        uses: ./.github/workflows/deploy.yaml
        with:
          foo: bar
      - run: echo ${{steps.run.outputs}}

          